spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/keycloak
    username: keycloak
    password: keycloak
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.jboss.narayana.jta
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: false
  profiles:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.urls.auth}/realms/${keycloak.realm}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

jwt:
  auth:
    converter:
      resource-id: ${keycloak.client}

keycloak:
  realm: spring-boot-keycloak
  domain: localhost:8081
  adminClientId: admin-cli
  adminClientSecret: ${ADMIN_CLIENT_SECRET}
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}

server:
  port: 8443
  servlet:
    context-path: /organization-education
    session:
      cookie:
        same-site: strict
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.p12
    key-store-password: ${TLS_PASSWORD}
    protocol: TLS
    enabled-protocols: TLSv1.3

logging:
  file:
    name: ./logs/organization_education.log