spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/keycloak
    username: keycloak
    password: keycloak
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.jboss.narayana.jta
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: false
  profiles:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.urls.auth}/realms/${keycloak.realm}

jwt:
  auth:
    converter:
      resource-id: ${keycloak.client}

keycloak:
  realm: spring-boot-keycloak
  domain: localhost:8081
  adminClientId: admin-cli
  adminClientSecret:
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}

server:
  port: 8181
  servlet:
    context-path: /organization-education

logging:
  file:
    name: ./logs/organization_education.log